version: '3.7'

services:

#  api:
#    build: .
#    container_name: gaivotaApi
#    volumes:
#      - ./weather:/opt/weather/weather
#      - ./tests:/opt/weather/tests
#      - ./files:/opt/weather/files
#      - ./Makefile:/opt/weather/Makefile
#    ports:
#      - "8081:8081"
#    depends_on: ["db-postgre"]
#    environment:
#      - APP_PORT=8081
#      - SQL_USER=postgres
#      - SQL_PWD=123456
#      - SQL_HOST=gaivotaDatabase
#      - SQL_DB=gaivota
#      - SQL_PORT=5432
#      - SQL_SCHEMA=gaivota
#      - APP_DEBUG=1
#      - APP_VERSION=1.0.0
#      - APP_TITLE=Gaivota Teste Api
#    networks:
#      - gv_networks

  db-postgre:
    container_name: gaivotaDatabase
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123456
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    ports:
      - "5432:5432"
    volumes:
      - ./prepare_database/postgree/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gv_networks

  pgadmin:
    container_name: gaivotaPgadmin
    image: dpage/pgadmin4:latest
    ports:
      - 15432:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=leandro@gaivota.ai
    networks:
      - gv_networks

  sonarqube:
    container_name: gaivotaSonar
    image: sonarqube:7.9.4-community
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=v07IGCFCF83Z95NX
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - gv_networks

networks:
  gv_networks:
    name: gv_networks