version: '3.7'

services:
  db-postgre:
    container_name: gaivota.database
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123456
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgree/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gv_networks

  pgadmin:
    container_name: gaivota.pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - 15432:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=leandro@gaivota.ai
    networks:
      - gv_networks

networks:
  gv_networks:
    name: gv_networks